### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Mo7amedSMahdi** [Mo7amedSMahdi/space-travelers-hub#63]
## Hello everyone,
we are very excited🤩🎉 to start working on our project with new things to learn about Kanban boards, React, and Redux.

So let me introduce ourselves to you, We are a team of two students:  
* [Mohammed Salah(Medo)](https://github.com/Mo7amedSMahdi).
* [Adekunle Akinkunmi Ismail](https://github.com/ismailakinkunmi).
### Thanks in advance.

**Comment by Kingstalux** [comment]
Hi @Mo7amedSMahdi and @ismailakinkunmi,
# Status: Approved ✔️ ✔️ ✔️ 
 
![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966](https://user-images.githubusercontent.com/85113567/168593144-f742a370-5ce8-4275-a775-3ae1a6263768.gif)

## Highlights 👏 
✅ All cards have assignees 🔥 
✅ All tasks have been distributed fairly 👍 

Good job so far 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
